import "bootstrap/dist/css/bootstrap.css";

import { ClerkProvider } from "@clerk/nextjs/app-beta";

export const metadata = {
  title: "Zachary's Website",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <ClerkProvider>
            {/* <NavBar additionalLinks={additionalLinks} /> */}
            {/* <div className="container">{children}</div> */}
            {children}
          </ClerkProvider>
          <footer>
            <div className="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
              Copyright 2023 by Zachary Roux.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
