import "bootstrap/dist/css/bootstrap.css";

import { ClerkProvider, currentUser } from "@clerk/nextjs/app-beta";
import type { User } from "@clerk/nextjs/api";
import NavBar from "./common/NavBar";

export const metadata = {
  title: "Zachary's Website",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user: User | null = await currentUser();

  const additionalLinks = [{ href: "/reviews", label: "Movie reviews" }];

  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <NavBar user={user} additionalLinks={additionalLinks} />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
