import "bootstrap/dist/css/bootstrap.css";

import { ClerkProvider } from "@clerk/nextjs/app-beta";

export const metadata = {
  title: "Zachary's Website",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>{children}</body>
      </ClerkProvider>
    </html>
  );
}
