import "bootstrap/dist/css/bootstrap.css";

import Header from "../../common/Header";

export const metadata = {
  title: "Zachary's Movie Reviews",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const additionalLinks = [{ href: "/reviews", label: "Movie reviews" }];

  return (
    <html lang="en">
      <body>
        <Header additionalLinks={additionalLinks} />
        <div className="container py-3">{children}</div>
      </body>
    </html>
  );
}
