import "bootstrap/dist/css/bootstrap.css";
import { currentUser } from "@clerk/nextjs/app-beta";
import type { User } from "@clerk/nextjs/api";

import Header from "../../common/Header";

export const metadata = {
  title: "Zachary's Movie Reviews",
  description: "Generated by create next app",
};

export default async function ReviewLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user: User | null = await currentUser();

  const additionalLinks = [{ href: "/reviews", label: "Movie reviews" }];

  return (
    <>
      <Header additionalLinks={additionalLinks} user={user} />
      <div className="container py-3">{children}</div>
    </>
  );
}
