import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="container py-3">{children}</div>;
}
